baseURL = "https://fjrodriguez.github.io"
languageCode = "eo"
languageName = "Esperanto"
title = 'Paco Rodríguez Site'
theme = "LoveIt"
# whether to include Chinese/Japanese/Korean
# 是否包括中日韩文字
hasCJKLanguage = true

[params]
  # site default theme ["auto", "light", "dark"]
  # 网站默认主题 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # date format
  # 日期格式
  dateFormat = "01-02-2006"
  # website title for Open Graph and Twitter Cards
  # 网站标题, 用于 Open Graph 和 Twitter Cards
  title = "Blog de Paco"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  # 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
  description = "Blog personal de Paco"
  # website images for Open Graph and Twitter Cards
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  # images = ["/logo.png"]

  # Author config
  # 作者配置
  [params.author]
    name = "Paco Rodríguez"
    email = "pako.rodriguez@gmail.com"
    link = "https://fjrodriguez.github.com"

  # Header config
  # 页面头部导航栏配置
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
 
   # Section (all posts) page config
  # Section (所有文章) 页面配置
  [params.section]
    # special amount of posts in each section page
    # section 页面每页显示文章数量
    paginate = 20
    # date format (month and day)
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # amount of RSS pages
    # RSS 文章数目
    rss = 10

  # List (category or tag) page config
  # List (目录或标签) 页面配置
  [params.list]
    # special amount of posts in each list page
    # list 页面每页显示文章数量
    paginate = 20
    # date format (month and day)
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # amount of RSS pages
    # RSS 文章数目
    rss = 10

  # Home page config
  # 主页信息设置
  [params.home]
    # amount of RSS pages
    # RSS 文章数目
    rss = 10
    # Home page profile
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = "pako.rodriguez@gmail.com"
      # URL of avatar shown in home page
      # 主页显示头像的 URL
      avatarURL = "/images/avatar.png"

  # Social config in home page
  # 主页的社交信息设置
  [params.social]
    GitHub = "fjrodriguez"
    Linkedin = "fcojesusrm"
    X = "pakuco"
    Instagram = "pakuco"

  # Page global config
  # 文章页面全局配置
  [params.page]
    # whether to enable the ruby extended syntax
    # 是否使用 ruby 扩展语法
    ruby = true
    [params.page.code]
      # whether to show the copy button of the code block
      # 是否显示代码块的复制按钮
      copy = true
    [params.page.share]
      enable = false
      X = true
      Linkedin = true

  # Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2025
    license = '<a rel="license external nofollow noopener noreffer" href="https://opensource.org/license/mit" target="_blank">MIT License</a>'



